import React,{useMemo,useRef}from'react';import{Canvas,useFrame}from'@react-three/fiber';import{Float,Stars}from'@react-three/drei';import{EffectComposer,Bloom,Vignette}from'@react-three/postprocessing';import*as THREE from'three';

function Tube({p=[0,0,0],r=0,fill='#c01435'}){const g=useRef();useFrame((s)=>{g.current.rotation.z=r+Math.sin(s.clock.elapsedTime*.7+p[0])*.05});return <group ref={g} position={p} rotation={[0,0,r]}><mesh><cylinderGeometry args={[.22,.22,1.7,32]}/><meshPhysicalMaterial color="#b7e9e4" transparent opacity={.22} roughness={.05} transmission={.65}/></mesh><mesh position={[0,-.42,0]}><cylinderGeometry args={[.19,.19,.72,32]}/><meshPhysicalMaterial color={fill} emissive={fill} emissiveIntensity={.4} roughness={.2}/></mesh><mesh position={[0,.91,0]}><cylinderGeometry args={[.245,.245,.18,32]}/><meshStandardMaterial color="#071d20" metalness={.8} roughness={.25}/></mesh></group>}

function Cell({p,s=1}){const ref=useRef();useFrame((st,d)=>{ref.current.rotation.x+=d*.2;ref.current.rotation.y+=d*.35;ref.current.position.y=p[1]+Math.sin(st.clock.elapsedTime*.8+p[0])*0.2});return <mesh ref={ref} position={p} scale={s}><torusGeometry args={[.3,.12,16,48]}/><meshPhysicalMaterial color="#b7133d" emissive="#6e071e" emissiveIntensity={.7} roughness={.45}/></mesh>}

function Helix(){const pts=useMemo(()=>Array.from({length:42},(_,i)=>{const y=(i-21)*.12,a=i*.52;return [Math.cos(a)*.65,y,Math.sin(a)*.65]}),[]);const ref=useRef();useFrame((_,d)=>ref.current.rotation.y+=d*.18);return <group ref={ref} position={[3.2,0,-1]}>{pts.map((p,i)=><group key={i}><mesh position={p}><sphereGeometry args={[.055,10,10]}/><meshBasicMaterial color={i%2?'#46ffe1':'#d9ffff'}/></mesh>{i%2===0&&<mesh position={[0,p[1],0]} rotation={[0,-i*.52,Math.PI/2]}><cylinderGeometry args={[.012,.012,1.25,6]}/><meshBasicMaterial color="#168f84"/></mesh>}</group>)}</group>}

function BrainCore(){const ref=useRef(),r1=useRef(),r2=useRef();useFrame((s,d)=>{ref.current.rotation.y+=d*.12;ref.current.rotation.x=THREE.MathUtils.lerp(ref.current.rotation.x,-s.pointer.y*.18,.03);r1.current.rotation.z+=d*.2;r2.current.rotation.x-=d*.15});return <group ref={ref}><Float speed={1.5} floatIntensity={.6}><mesh><icosahedronGeometry args={[1.2,4]}/><meshPhysicalMaterial color="#082026" emissive="#2df7d6" emissiveIntensity={1.2} wireframe/></mesh><mesh scale={.62}><icosahedronGeometry args={[1.2,2]}/><meshPhysicalMaterial color="#0c3a3d" emissive="#3dffe2" emissiveIntensity={2} transparent opacity={.45}/></mesh></Float><mesh ref={r1}><torusGeometry args={[1.75,.012,8,160]}/><meshBasicMaterial color="#4affe4"/></mesh><mesh ref={r2} rotation={[1.2,.5,0]}><torusGeometry args={[2.1,.008,8,160]}/><meshBasicMaterial color="#157c74"/></mesh></group>}

function Scene({phase}){const world=useRef();useFrame((s)=>{const targets=[[0,0,7],[-2.8,0,6],[2.4,.2,6],[0,0,7]];const t=targets[phase]||targets[0];s.camera.position.x=THREE.MathUtils.lerp(s.camera.position.x,t[0]+s.pointer.x*.25,.025);s.camera.position.y=THREE.MathUtils.lerp(s.camera.position.y,t[1]+s.pointer.y*.15,.025);s.camera.position.z=THREE.MathUtils.lerp(s.camera.position.z,t[2],.025);s.camera.lookAt(0,0,0)});return <group ref={world}><BrainCore/><group position={[-3,0,-.7]}><Tube p={[-.6,.3,0]} r={-.25}/><Tube p={[.15,-.2,.2]} r={.16} fill="#6c1a78"/><Tube p={[.75,.45,-.2]} r={-.08} fill="#d39822"/></group><Helix/>{[[-1.8,1,-1],[-2,-1,.3],[-1.1,-1.6,-1],[1.5,1.4,-1],[2,-1.2,.5],[.8,-1.8,-.7]].map((p,i)=><Cell key={i} p={p} s={.6+i%3*.18}/>)}</group>}

export default function World({phase=0}){return <Canvas camera={{position:[0,0,7],fov:48}} dpr={[1,1.5]} gl={{antialias:true,alpha:true}}><fog attach="fog" args={['#020709',7,16]}/><ambientLight intensity={.25}/><pointLight position={[0,2,4]} color="#4affe4" intensity={16}/><pointLight position={[-4,-1,2]} color="#c21443" intensity={7}/><Scene phase={phase}/><Stars radius={70} depth={30} count={700} factor={2} fade speed={.25}/><EffectComposer><Bloom luminanceThreshold={.1} intensity={1.25} mipmapBlur/><Vignette offset={.12} darkness={.8}/></EffectComposer></Canvas>}