import"dotenv/config";import crypto from"crypto";import express from"express";import cors from"cors";import multer from"multer";import helmet from"helmet";import{rateLimit}from"express-rate-limit";import pinoHttp from"pino-http";import{z}from"zod";import{repository}from"./repository.js";import{normalizeResults}from"./normalizer.js";import{registryView}from"./registry.js";import{DEMO_REFERENCE_SET}from"./reference.js";import{analyzeLaboratoryCase}from"./engine.js";import{inspectFile,uploadPolicy}from"./ingestion/security.js";import{extractTabular,stageUnstructured}from"./ingestion/adapters.js";import{scoreAndResolve,buildVerificationQueue}from"./ingestion/pipeline.js";import{ingestionStore}from"./ingestion/store.js";import{inspectDocument}from"./document/inspect.js";import{orchestrate}from"./orchestration/orchestrator.js";import{PROMPTS}from"./orchestration/prompts.js";import{auth,allow,issueDemoToken,demoUsers}from"./auth/auth.js";import{transitionCase,computeDiff}from"./workflow/workflow.js";import{workflowStore}from"./workflow/store.js";import{processIntegration,integrationStore}from"./integration/gateway.js";import{CONNECTOR_CONTRACTS}from"./integration/contracts.js";import{env}from"./config/env.js";import{logger}from"./observability/logger.js";import{connectInfra}from"./infra/clients.js";import{putObject}from"./storage/objectStore.js";import{enqueueJob}from"./queue/jobs.js";import{durableIngestionStore}from"./ingestion/durableStore.js";import{processMedicalDocument}from"./document/intelligence.js";import{executeGovernedAI}from"./ai/governance/pipeline.js";import{providerStatus}from"./ai/provider.js";import{knowledgeSummary,listKnowledgeTests,getKnowledgeTest,convertKnowledgeValue}from"./knowledge/registry.js";import{addReferenceSet,resolveReferenceSet,addCriticalPolicy,evaluateCritical,referenceStore}from"./knowledge/reference.js";import{proposeKnowledgeChange,reviewKnowledgeChange,listKnowledgeChanges}from"./knowledge/governance.js";import{assertTenantAccess}from"./security/tenant.js";import{preScanFile}from"./security/fileScan.js";import{extractionMetrics,verificationMetrics,aiRunMetrics}from"./metrics/validationMetrics.js";import{operationalStatus}from"./ops/status.js";
const app=express();let infraState={postgres:false,redis:false,errors:[]};
app.use(pinoHttp({logger,genReqId:req=>req.headers["x-request-id"]||crypto.randomUUID()}));
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors());
app.use(rateLimit({windowMs:60_000,limit:240,standardHeaders:"draft-7",legacyHeaders:false}));
app.use(express.json({limit:"2mb"}));const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:uploadPolicy.maxBytes,files:1}});
const input=z.object({externalId:z.string().min(3).max(64),displayName:z.string().min(1).max(120),specimen:z.string().max(120).nullable().optional(),results:z.array(z.object({testCode:z.string(),valueText:z.union([z.string(),z.number()]).transform(String),numericValue:z.number().nullable().optional(),unit:z.string().nullable().optional()})).min(1).max(500)});
const demo={externalId:"DEMO-0248",displayName:"Demonstration Case",specimen:"EDTA Whole Blood",results:[["HGB",9.8,"g/dL"],["MCV",68,"fL"],["MCH",21,"pg"],["RDW",18.2,"%"],["WBC",7.4,"×10⁹/L"],["PLT",312,"×10⁹/L"]].map(([testCode,valueText,unit])=>({testCode,valueText:String(valueText),numericValue:valueText,unit}))};
async function ensureDemo(){if(!await repository.getCase(demo.externalId)){const results=normalizeResults(demo.results);await repository.saveCase({...demo,results})}}
app.get("/api/health",(req,res)=>res.json({ok:true,service:"AZEZ LAB AI Core API",version:"1.0.0-rc17",repository:repository.mode(),infra:infraState}));
app.get("/api/ready",(req,res)=>{const ready=infraState.postgres&&infraState.redis;res.status(ready?200:503).json({ready,infra:infraState})});
app.get("/api/registry/tests",(req,res)=>res.json(registryView()));app.get("/api/reference-sets/demo",(req,res)=>res.json(DEMO_REFERENCE_SET));app.post("/api/document-intelligence/extract",upload.single("report"),async(req,res)=>{
 const scan=preScanFile(req.file||{});if(!scan.accepted)return res.status(415).json({error:"FILE_SECURITY_REJECTED",scan});const inspection=inspectFile(req.file);
 if(!inspection.accepted)return res.status(415).json({error:"FILE_REJECTED",inspection});
 if(!["pdf","image"].includes(inspection.sourceType))return res.status(400).json({error:"DOCUMENT_TYPE_REQUIRED"});
 try{
  const object=await putObject({buffer:req.file.buffer,originalName:req.file.originalname,mimeType:req.file.mimetype});
  const result=await processMedicalDocument(req.file,inspection.sourceType);
  res.status(200).json({...result,objectKey:object.objectKey,sha256:object.sha256});
 }catch(e){req.log?.error({error:e.message},"document intelligence failed");res.status(422).json({error:"DOCUMENT_EXTRACTION_FAILED",message:e.message})}
});
app.get("/api/ingestion/policy",(req,res)=>res.json(uploadPolicy));
app.post("/api/ingestion",upload.single("report"),async(req,res)=>{const scan=preScanFile(req.file||{});if(!scan.accepted)return res.status(415).json({error:"FILE_SECURITY_REJECTED",scan});const inspection=inspectFile(req.file);if(!inspection.accepted)return res.status(415).json({error:"FILE_REJECTED",inspection});let extraction;try{extraction=extractTabular(req.file,inspection.sourceType)||stageUnstructured(inspection.sourceType);if(inspection.sourceType==="pdf"||inspection.sourceType==="image"){extraction={...extraction,documentInspection:await inspectDocument(req.file,inspection.sourceType)}}}catch(e){return res.status(422).json({error:"EXTRACTION_FAILED",message:e.message})}const fields=scoreAndResolve(extraction.fields||[]),queue=buildVerificationQueue(fields);const status=extraction.requiresOcr?"NEEDS_VERIFICATION":queue.length?"NEEDS_VERIFICATION":"EXTRACTED";const object=await putObject({buffer:req.file.buffer,originalName:req.file.originalname,mimeType:req.file.mimetype});
const payload={originalName:req.file.originalname,objectKey:object.objectKey,mimeType:req.file.mimetype,sizeBytes:req.file.size,sha256:inspection.sha256,sourceType:inspection.sourceType,adapter:extraction.adapter,status,fields,verificationQueue:queue,requiresOcr:!!extraction.requiresOcr,documentInspection:extraction.documentInspection||null,message:extraction.message||null};
const job=infraState.postgres?await durableIngestionStore.create(payload):ingestionStore.create(payload);
let queueJobId=null;
if(infraState.redis&&infraState.postgres){const queued=await enqueueJob("INGESTION_POSTPROCESS",{ingestionJobId:job.id});queueJobId=String(queued.id);await durableIngestionStore.update(job.id,{queueJobId})}
res.status(201).json({...job,objectKey:object.objectKey,queueJobId});});
app.get("/api/ingestion",async(req,res)=>res.json(infraState.postgres?await durableIngestionStore.list():ingestionStore.list()));
app.get("/api/ingestion/:id",async(req,res)=>{const j=infraState.postgres?await durableIngestionStore.get(req.params.id):ingestionStore.get(req.params.id);if(!j)return res.status(404).json({error:"INGESTION_NOT_FOUND"});res.json(j)});
app.post("/api/ingestion/:id/verify",(req,res)=>{const j=ingestionStore.get(req.params.id);if(!j)return res.status(404).json({error:"INGESTION_NOT_FOUND"});const decisions=z.array(z.object({rowIndex:z.number().int().positive(),action:z.enum(["ACCEPT","CORRECT","REJECT"]),testCode:z.string().optional(),valueText:z.string().optional(),unit:z.string().nullable().optional()})).safeParse(req.body.decisions);if(!decisions.success)return res.status(400).json({error:"VALIDATION_ERROR",issues:decisions.error.issues});let fields=j.fields.map(f=>{const d=decisions.data.find(x=>x.rowIndex===f.rowIndex);if(!d)return f;if(d.action==="REJECT")return{...f,verificationStatus:"REJECTED",reviewed:true};const changed={...f,sourceTestCode:d.testCode??f.sourceTestCode,sourceValue:d.valueText??f.sourceValue,sourceUnit:d.unit??f.sourceUnit};return{...scoreAndResolve([changed])[0],verificationStatus:"ACCEPTED",reviewed:true,corrected:d.action==="CORRECT"}});const pending=buildVerificationQueue(fields);const updated=ingestionStore.update(j.id,{fields,verificationQueue:pending,status:pending.length?"NEEDS_VERIFICATION":"VERIFIED"});res.json(updated)});
app.post("/api/ingestion/:id/create-case",async(req,res)=>{const j=ingestionStore.get(req.params.id);if(!j)return res.status(404).json({error:"INGESTION_NOT_FOUND"});if(j.status!=="VERIFIED"&&j.status!=="EXTRACTED")return res.status(409).json({error:"VERIFICATION_REQUIRED"});const meta=z.object({externalId:z.string().min(3),displayName:z.string().min(1),specimen:z.string().nullable().optional()}).safeParse(req.body);if(!meta.success)return res.status(400).json({error:"VALIDATION_ERROR"});const accepted=j.fields.filter(f=>f.verificationStatus==="ACCEPTED").map(f=>({testCode:f.canonicalCode,valueText:f.sourceValue,numericValue:f.numericValue,unit:f.sourceUnit}));if(!accepted.length)return res.status(422).json({error:"NO_VERIFIED_RESULTS"});const results=normalizeResults(accepted);const c=await repository.saveCase({...meta.data,results});ingestionStore.update(j.id,{caseExternalId:c.externalId,status:"VERIFIED"});res.status(201).json(c)});
app.get("/api/integration/contracts",auth,(req,res)=>res.json(CONNECTOR_CONTRACTS));
app.post("/api/integration/hl7",auth,allow("SYSTEM_ADMIN","ORG_ADMIN","LAB_SPECIALIST"),(req,res)=>{const raw=req.body?.message,idempotencyKey=req.headers["idempotency-key"]||req.body?.idempotencyKey;if(!raw||!idempotencyKey)return res.status(400).json({error:"MESSAGE_AND_IDEMPOTENCY_KEY_REQUIRED"});const out=processIntegration({protocol:"HL7_V2",payload:raw,idempotencyKey:String(idempotencyKey),sourceCode:req.body?.sourceCode||"HL7-DEMO",organizationCode:req.user.organizationCode});res.status(out.duplicate?200:out.message.status==="DEAD_LETTER"?422:202).json(out)});
app.post("/api/integration/fhir",auth,allow("SYSTEM_ADMIN","ORG_ADMIN","LAB_SPECIALIST"),(req,res)=>{const idempotencyKey=req.headers["idempotency-key"]||req.body?.idempotencyKey,payload=req.body?.resource||req.body;if(!idempotencyKey)return res.status(400).json({error:"IDEMPOTENCY_KEY_REQUIRED"});const out=processIntegration({protocol:"FHIR_R4",payload,idempotencyKey:String(idempotencyKey),sourceCode:req.body?.sourceCode||"FHIR-DEMO",organizationCode:req.user.organizationCode});res.status(out.duplicate?200:out.message.status==="DEAD_LETTER"?422:202).json(out)});
app.get("/api/integration/messages",auth,allow("SYSTEM_ADMIN","ORG_ADMIN","LAB_SPECIALIST","REVIEWER"),(req,res)=>res.json(integrationStore.listMessages()));
app.get("/api/integration/dead-letter",auth,allow("SYSTEM_ADMIN","ORG_ADMIN"),(req,res)=>res.json(integrationStore.deadLetters()));
app.get("/api/integration/reconciliation",auth,allow("SYSTEM_ADMIN","ORG_ADMIN","LAB_SPECIALIST"),(req,res)=>res.json(integrationStore.reconciliation()));
app.post("/api/integration/reconciliation/:id/resolve",auth,allow("SYSTEM_ADMIN","ORG_ADMIN","LAB_SPECIALIST"),(req,res)=>{const item=integrationStore.resolveReconciliation(req.params.id,req.body?.mapping||null);if(!item)return res.status(404).json({error:"RECONCILIATION_NOT_FOUND"});res.json(item)});
app.post("/api/auth/demo-login",(req,res)=>{const token=issueDemoToken(req.body?.email);if(!token)return res.status(401).json({error:"DEMO_USER_NOT_FOUND"});const user=demoUsers.find(x=>x.email===req.body.email);res.json({token,user})});
app.get("/api/auth/demo-users",(req,res)=>res.json(demoUsers.map(({id,email,displayName,role,organizationCode})=>({id,email,displayName,role,organizationCode}))));
app.get("/api/cases/:id/workflow",auth,async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}const state=workflowStore.ensure(c.externalId);res.json({caseId:c.externalId,status:state.status,lock:workflowStore.getLock(c.externalId),reviews:workflowStore.reviewsFor(c.externalId),acknowledgments:workflowStore.acksFor(c.externalId)})});
app.post("/api/cases/:id/lock",auth,allow("LAB_SPECIALIST","REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}const out=workflowStore.lock(c.externalId,req.user.id,15);if(!out.ok)return res.status(409).json({error:"CASE_LOCKED",lock:out.lock});res.json(out.lock)});
app.delete("/api/cases/:id/lock",auth,async(req,res)=>{const ok=workflowStore.unlock(req.params.id,req.user.id);if(!ok)return res.status(403).json({error:"LOCK_OWNERSHIP_REQUIRED"});res.json({ok:true})});
app.post("/api/cases/:id/assign",auth,allow("ORG_ADMIN","SYSTEM_ADMIN"),async(req,res)=>{const user=demoUsers.find(x=>x.id===req.body?.userId);if(!user)return res.status(404).json({error:"USER_NOT_FOUND"});res.json(workflowStore.assign(req.params.id,user.id,req.user.id))});
app.post("/api/cases/:id/reviews",auth,allow("REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}const lock=workflowStore.getLock(c.externalId);if(lock&&lock.userId!==req.user.id)return res.status(409).json({error:"CASE_LOCKED_BY_OTHER_REVIEWER"});workflowStore.lock(c.externalId,req.user.id,15);const decision=req.body?.decision;if(!["APPROVED","REJECTED","CHANGES_REQUESTED"].includes(decision))return res.status(400).json({error:"INVALID_REVIEW_DECISION"});const source=(c.analyses?.[0]?.patternJson)||null,finalOutput=req.body?.finalOutput??source,diff=computeDiff(source,finalOutput);const review=workflowStore.addReview({caseId:c.externalId,reviewerId:req.user.id,reviewer:req.user.displayName,decision,notes:req.body?.notes||null,sourceOutput:source,finalOutput,diff});const target=decision==="APPROVED"?"REVIEWED":"READY";workflowStore.setStatus(c.externalId,target);workflowStore.unlock(c.externalId,req.user.id);await repository.audit(c.id,req.user.id,"REVIEW_"+decision,{reviewId:review.id,diffSummary:{changed:diff.changed,changeCount:diff.changeCount}});res.status(201).json(review)});
app.post("/api/cases/:id/critical-acknowledgments",auth,allow("LAB_SPECIALIST","REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}if(!req.body?.signalKey)return res.status(400).json({error:"SIGNAL_KEY_REQUIRED"});const ack=workflowStore.acknowledge({caseId:c.externalId,userId:req.user.id,user:req.user.displayName,signalKey:req.body.signalKey,note:req.body.note||null});if(!ack)return res.status(409).json({error:"SIGNAL_ALREADY_ACKNOWLEDGED"});await repository.audit(c.id,req.user.id,"CRITICAL_SIGNAL_ACKNOWLEDGED",{signalKey:ack.signalKey});res.status(201).json(ack)});
app.get("/api/ops/status",auth,(req,res)=>res.json(operationalStatus({infraState,provider:providerStatus(),knowledge:knowledgeSummary()})));
app.post("/api/validation/extraction-metrics",auth,allow("REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>res.json(extractionMetrics(req.body?.expected||[],req.body?.actual||[])));
app.post("/api/validation/verification-metrics",auth,allow("REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>res.json(verificationMetrics(req.body?.fields||[])));
app.post("/api/validation/ai-run-metrics",auth,allow("REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>res.json(aiRunMetrics(req.body?.runs||[])));
app.get("/api/knowledge/summary",auth,(req,res)=>res.json(knowledgeSummary()));
app.get("/api/knowledge/tests",auth,(req,res)=>res.json(listKnowledgeTests({discipline:req.query.discipline,q:req.query.q})));
app.get("/api/knowledge/tests/:code",auth,(req,res)=>{const x=getKnowledgeTest(req.params.code);if(!x)return res.status(404).json({error:"KNOWLEDGE_TEST_NOT_FOUND"});res.json(x)});
app.post("/api/knowledge/convert",auth,(req,res)=>{const out=convertKnowledgeValue(req.body?.testCode,req.body?.value,req.body?.from,req.body?.to);res.status(out.ok?200:422).json(out)});
app.post("/api/knowledge/reference-sets",auth,allow("ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>{try{res.status(201).json(addReferenceSet(req.body))}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/knowledge/reference-sets/resolve",auth,(req,res)=>res.json({referenceSet:resolveReferenceSet(req.body||{})}));
app.get("/api/knowledge/reference-sets",auth,(req,res)=>res.json(referenceStore.list()));
app.post("/api/knowledge/critical-policies",auth,allow("ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>{try{res.status(201).json(addCriticalPolicy(req.body))}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/knowledge/critical-policies/evaluate",auth,(req,res)=>res.json({signals:evaluateCritical({...req.body,organizationCode:req.user.organizationCode})}));
app.get("/api/knowledge/critical-policies",auth,(req,res)=>res.json(referenceStore.criticalPolicies()));
app.get("/api/knowledge/changes",auth,allow("ORG_ADMIN","SYSTEM_ADMIN","REVIEWER"),(req,res)=>res.json(listKnowledgeChanges()));
app.post("/api/knowledge/changes",auth,allow("ORG_ADMIN","SYSTEM_ADMIN","REVIEWER"),(req,res)=>res.status(201).json(proposeKnowledgeChange({...req.body,proposedBy:req.user.id})));
app.post("/api/knowledge/changes/:id/review",auth,allow("ORG_ADMIN","SYSTEM_ADMIN"),(req,res)=>{try{const p=reviewKnowledgeChange(req.params.id,{...req.body,reviewer:req.user.id});if(!p)return res.status(404).json({error:"KNOWLEDGE_CHANGE_NOT_FOUND"});res.json(p)}catch(e){res.status(400).json({error:e.message})}});
app.get("/api/ai/provider-status",auth,(req,res)=>res.json(providerStatus()));
app.post("/api/cases/:id/ai-analysis",auth,allow("LAB_SPECIALIST","REVIEWER","ORG_ADMIN","SYSTEM_ADMIN"),async(req,res)=>{
 await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}
 const evidence=(c.results||[]).map((r,i)=>({evidenceId:`EV-${String(i+1).padStart(4,"0")}`,testCode:r.testCode,value:r.numericValue,unit:r.unit,flag:r.flag,referenceLow:r.referenceLow,referenceHigh:r.referenceHigh}));
 const patterns=c.analyses?.[0]?.patternJson?.observations||[];
 if(!evidence.length)return res.status(409).json({error:"NO_VERIFIED_EVIDENCE"});
 try{
  const run=await executeGovernedAI({evidence,patterns});
  await repository.audit(c.id,req.user.id,"REAL_AI_ANALYSIS_COMPLETED",{governance:run.governance});
  res.json(run);
 }catch(e){
  req.log?.error({error:e.message,details:e.details},"governed AI analysis rejected");
  await repository.audit(c.id,req.user.id,"AI_ANALYSIS_REJECTED",{reason:e.message,details:e.details||null});
  res.status(422).json({error:e.message,details:e.details||null});
 }
});
app.get("/api/orchestration/prompts",(req,res)=>res.json(Object.entries(PROMPTS).map(([name,p])=>({name,version:p.version,purpose:p.purpose,constraints:p.constraints}))));
app.post("/api/cases/:id/orchestrate",auth,async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}const deterministic=analyzeLaboratoryCase(c);try{const run=await orchestrate({caseData:c,deterministicOutput:deterministic,promptVersion:req.body?.promptVersion||"LAB_SUMMARY_V1"});await repository.saveOrchestration(c,run);await repository.audit(c.id,"ai-orchestrator","ORCHESTRATION_"+run.status,{provider:run.provider,model:run.model,prompt:run.prompt,gate:run.gate});if(run.status!=="COMPLETED")return res.status(422).json(run);res.json(run)}catch(e){res.status(503).json({error:"ORCHESTRATION_FAILED",message:e.message})}});
app.get("/api/cases",auth,async(req,res)=>{await ensureDemo();res.json(await repository.listCases())});app.get("/api/cases/:id",auth,async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}res.json(c)});
app.post("/api/cases",async(req,res)=>{const p=input.safeParse(req.body);if(!p.success)return res.status(400).json({error:"VALIDATION_ERROR",issues:p.error.issues});if(await repository.getCase(p.data.externalId))return res.status(409).json({error:"CASE_EXISTS"});const results=normalizeResults(p.data.results),errors=results.filter(x=>x.error);if(errors.length)return res.status(422).json({error:"NORMALIZATION_FAILED",issues:errors});const c=await repository.saveCase({...p.data,results});res.status(201).json(c)});
app.post("/api/cases/:id/analyze",auth,async(req,res)=>{await ensureDemo();const c=await repository.getCase(req.params.id);if(!c)return res.status(404).json({error:"CASE_NOT_FOUND"});try{assertTenantAccess(req.user,c)}catch(e){return res.status(e.status||403).json({error:e.message})}const output=analyzeLaboratoryCase(c);await repository.saveAnalysis(c,output);await repository.audit(c.id,"pattern-engine","ANALYSIS_COMPLETED",{engine:output.engine});res.json({caseId:c.externalId,status:"COMPLETED",repository:repository.mode(),output})});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(413).json({error:"UPLOAD_LIMIT",code:err.code});console.error(err);res.status(500).json({error:"INTERNAL_ERROR"})});const port=env.PORT;
try{infraState=await connectInfra()}catch(e){logger.fatal({error:e.message},"Core startup failed");process.exit(1)}
app.listen(port,()=>logger.info({port,infraState},"AZEZ LAB AI V11 Core started"));
